version: "3"

services:
  web: 
    build: .
    command: sh -c "uvicorn energy_usage_optimizer_api.main:app --reload --port=8000 --host=0.0.0.0"
    ports: 
      - 8000:8000 
    volumes:
      - .:/app